sudo: false
language: node_js
node_js:
  - "5.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - mongodb
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - develop
before_install:
  - npm i -g npm@^2.0.0
  - bower install
before_script:
  - npm prune
script:
  - run gulp build
  - npm test
  - npm run fend:test
  - npm run check-coverage
after_success:
  - npm run report-coverage
  - npm run coveralls

deploy:
  provider: heroku
  api_key:
    develop: e32c893b-cda7-4512-b544-eaf96ca8bf6f
    production: e32c893b-cda7-4512-b544-eaf96ca8bf6f
  app:
    develop: dockip-develop
    production: dockip-production