sudo: false
language: node_js
node_js:
  - "5.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - mongodb
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - develop
    - master
before_install:
  - npm i -g npm@^2.0.0
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - npm prune
  - npm install
  - npm install -g gulp
  - npm install -g bower
  - bower install
  - gulp build
script:
  - npm test
  - npm run fend:test
after_success:
  - npm run report-coverage
  - npm run coveralls
deploy:
  provider: heroku
  api_key: e32c893b-cda7-4512-b544-eaf96ca8bf6f
  app:
    develop: dockip-develop
    master: dockip
after_deploy:
  - gulp heroku